---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
      
  - name: install httpd package
    yum:
      name: httpd 
      
  - name: install flask package
    yum:
      name: flask
