---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
      
  - name: install httpd package
    yum:
      name: httpd 
      state: latest  #to get the latest version of package

 - name: remove httpd package
   yum:
     name: httpd
     state: absent
